--1) 어제 만든 SCORE_STGR 테이블의 SNO 컬럼에 INDEX를 추가하세요.
CREATE INDEX SCORE_STGR_INDEX
ON SCORE_STGR(SNO);

SELECT * FROM SCORE_STGR;

SELECT UIC.INDEX_NAME
     , UIC.COLUMN_NAME
     , UIC.COLUMN_POSITION
     , UI.UNIQUENESS
FROM USER_INDEXES UI
         JOIN USER_IND_COLUMNS UIC
              ON UI.INDEX_NAME = UIC.INDEX_NAME
                  AND UI.TABLE_NAME IN ('SCORE_STGR')
ORDER BY UI.TABLE_NAME, UIC.INDEX_NAME, UIC.COLUMN_POSITION;

--2) 어제 만든 ST_COURSEPF 테이블의 SNO, CNO, PNO 다중 컬럼에 INDEX를 추가하세요.
CREATE INDEX ST_COURSEPF_INDEX
ON ST_COURSEPF(SNO, CNO, PNO);