--1. DDL
--1-1. 다른 테이블 참조하여 테이블 생성
CREATE TABLE COURSE_PROFESSOR(CNO, CNAME, PNO, PNAME, AVGRES)
    AS SELECT CNO
            , C.CNAME
            , PNO
            , P.PNAME
            , ROUND(AVG(RESULT), 2)
            FROM COURSE C
            NATURAL JOIN SCORE SC
            NATURAL JOIN PROFESSOR P
            GROUP BY CNO, C.CNAME, PNO, P.PNAME;

SELECT * FROM COURSE_PROFESSOR;

--STUDENT의 SNO, SNAME ,MAHOR ,SYEAR 학생별 RESULT ,GRADE
CREATE TABLE STUDENT_SCORE_GRADE(SNO, SNAME ,MAHOR ,SYEAR ,RESULT ,GRADE)
    AS SELECT SNO
            , ST.SNAME
            , ST.MAJOR
            , ST.SYEAR
            , SC.RESULT
            , SG.GRADE
            FROM STUDENT ST
            NATURAL JOIN SCORE SC
            JOIN SCGRADE SG
            ON SC.RESULT BETWEEN SG.LOSCORE AND SG.HISCORE;

DROP TABLE STUDENT_SCORE_GRADE;
SELECT * FROM STUDENT_SCORE_GRADE;

--1-2. ALTER
--컬럼을 추가하는 ADD
--EMP_COPY 테이블에 ADDR컬럼 추가
ALTER TABLE EMP_COPY
    ADD ADDR VARCHAR2(50);

SELECT * FROM EMP_COPY;

--컬럼명을 변경하는 RENAME
--EMP_COPY 테이블에 SAL 컬럼을 SALARY로 변경
ALTER TABLE EMP_COPY
    RENAME COLUMN SAL TO SALARY;

--컬럼의 데이터타입을 변경하는 MODIFY
--EMP_COPY 테이블에 ENO컬럼의 데이터타입을 VARCHAR2(4) -> VARCHAR2(10)으로 변경
ALTER TABLE EMP_COPY
    MODIFY ENO VARCHAR2(10);

--컬럼을 삭제하는 DROP
--EMP_COPY 테이블에 ADDR컬럼삭제
ALTER TABLE EMP_COPY
    DROP COLUMN ADDR;


--1-3. 테이블을 삭제하는 DROP
CREATE TABLE SCORE_COPY
    AS SELECT * FROM SCORE;
SELECT * FROM SCORE_COPY;
--SCORE_COPY 테이블 삭제
DROP TABLE SCORE_COPY;

--1-4. RENAME
RENAME EMP_COPY TO EMP_COPY;

--1-5. TRUNCATE 테이블의 데이터 모두 삭제
TRUNCATE TABLE EMP_COPY;
SELECT * FROM EMP_COPY;